export const FETCH_HOSPITAL_REQUEST = 'FETCH_HOSPITAL_REQUEST';
export const FETCH_HOSPITAL_SUCCESS = 'FETCH_HOSPITAL_SUCCESS';
export const FETCH_HOSPITAL_ERROR = 'FETCH_HOSPITAL_ERROR';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const FETCH_SINGLE_HOSPITAL_REQUEST = 'FETCH_SINGLE_HOSPITAL_REQUEST';
export const FETCH_SINGLE_HOSPITAL_SUCCESS = 'FETCH_SINGLE_HOSPITAL_SUCCESS';
export const FETCH_SINGLE_HOSPITAL_ERROR = 'FETCH_SINGLE_HOSPITAL_ERROR';

export const UPDATE_HOSPITAL_REQUEST = 'UPDATE_HOSPITAL_REQUEST';
export const UPDATE_HOSPITAL_SUCCESS = 'UPDATE_HOSPITAL_SUCCESS';
export const UPDATE_HOSPITAL_ERROR = 'UPDATE_HOSPITAL_ERROR';

export const DELETE_HOSPITAL_REQUEST = 'DELETE_HOSPITAL_REQUEST';
export const DELETE_HOSPITAL_SUCCESS = 'DELETE_HOSPITAL_SUCCESS';
export const DELETE_HOSPITAL_ERROR = 'DELETE_HOSPITAL_ERROR';

// DONOR
export const FETCH_DONOR_REQUEST = 'FETCH_DONOR_REQUEST';
export const FETCH_DONOR_SUCCESS = 'FETCH_DONOR_SUCCESS';
export const FETCH_DONOR_ERROR = 'FETCH_DONOR_ERROR';

export const FETCH_SINGLE_DONOR_REQUEST = 'FETCH_SINGLE_DONOR_REQUEST';
export const FETCH_SINGLE_DONOR_SUCCESS = 'FETCH_SINGLE_DONOR_SUCCESS';
export const FETCH_SINGLE_DONOR_ERROR = 'FETCH_SINGLE_DONOR_ERROR';

export const UPDATE_DONOR_REQUEST = 'UPDATE_DONOR_REQUEST';
export const UPDATE_DONOR_SUCCESS = 'UPDATE_DONOR_SUCCESS';
export const UPDATE_DONOR_ERROR = 'UPDATE_DONOR_ERROR';

// RECIPIENT
export const FETCH_RECIPIENT_REQUEST = 'FETCH_RECIPIENT_REQUEST';
export const FETCH_RECIPIENT_SUCCESS = 'FETCH_RECIPIENT_SUCCESS';
export const FETCH_RECIPIENT_ERROR = 'FETCH_RECIPIENT_ERROR';

export const FETCH_SINGLE_RECIPIENT_REQUEST = 'FETCH_SINGLE_RECIPIENT_REQUEST';
export const FETCH_SINGLE_RECIPIENT_SUCCESS = 'FETCH_SINGLE_RECIPIENT_SUCCESS';
export const FETCH_SINGLE_RECIPIENT_ERROR = 'FETCH_SINGLE_RECIPIENT_ERROR';

export const UPDATE_RECIPIENT_REQUEST = 'UPDATE_RECIPIENT_REQUEST';
export const UPDATE_RECIPIENT_SUCCESS = 'UPDATE_RECIPIENT_SUCCESS';
export const UPDATE_RECIPIENT_ERROR = 'UPDATE_RECIPIENT_ERROR';

// Homepage
export const GET_TOTALDONATION = 'GET_TOTALDONATION';
export const GET_TOTALDONOR = 'GET_TOTALDONOR';
export const GET_TOTALRECIPIENT = 'GET_TOTALRECIPIENT';
export const GET_TOPDONORS = 'GET_TOPDONORS';

// register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// logout
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// manage events
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';

export const FETCH_ALLCODE_SCHEDULE_TIME_REQUEST = 'FETCH_ALLCODE_SCHEDULE_TIME_REQUEST';
export const FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS = 'FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS';
export const FETCH_ALLCODE_SCHEDULE_TIME_FAILED = 'FETCH_ALLCODE_SCHEDULE_TIME_FAILED';

// schedule
export const CREATE_SCHEDULES_SUCCESS = 'CREATE_SCHEDULES_SUCCESS';
export const CREATE_SCHEDULES_FAILED = 'CREATE_SCHEDULES_FAILED';
export const FETCH_SCHEDULES_BYID_SUCCESS = 'FETCH_SCHEDULES_BYID_SUCCESS';
export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS';

// booking
export const FETCH_NEWEST_DONOR_BOOKING_SUCCESS = 'FETCH_NEWEST_DONOR_BOOKING_SUCCESS';
export const FETCH_NEWEST_DONOR_BOOKING_ERROR = 'FETCH_NEWEST_DONOR_BOOKING_ERROR';
export const FETCH_ALL_BOOKING_BY_DONORID_SUCCESS = 'FETCH_ALL_BOOKING_BY_DONORID_SUCCESS';

// request
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS'
export const FETCH_REQUEST_EACH_RECIPIENT_SUCCESS = 'FETCH_REQUEST_EACH_RECIPIENT_SUCCESS'
export const MOVE_REQUEST_SUCCESS = 'MOVE_REQUEST_SUCCESS'

// notification
export const FETCH_NOTIFY_FOR_RECIPIENT_SUCCESS = 'FETCH_NOTIFY_FOR_RECIPIENT_SUCCESS'
export const FETCH_NOTIFY_FOR_DONOR_SUCCESS = 'FETCH_NOTIFY_FOR_DONOR_SUCCESS'

//loader
export const TURN_ON_LOADER = 'TURN_ON_LOADER';
export const TURN_OFF_LOADER = 'TURN_OFF_LOADER';

